service: my-node-app

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  app:
    image:
      uri: 767397831825.dkr.ecr.ap-northeast-1.amazonaws.com/my-node-app:latest
    events:
      - http:
          path: /api/users
          method: get
      - http:
          path: /api/users
          method: post
      - http:
          path: /api/users/{id}
          method: get
      - http:
          path: /api/users/{id}
          method: put
      - http:
          path: /api/users/{id}
          method: delete

package:
  exclude:
    - .git/**
    - .env
